# Examples for finding optimum source configurations through basin hopping.

In [1]:
from configOptimization import *

## Initializing the Configuration

First, we define the source type that we are working with. Suppose that firstly we would like to work with point sources at a distance from the capsule (radius a=1) of d=4.
We first require the a_l coefficients of the Legendre expansion, which fully defines the source type.

In [2]:
aLValues=aLValuesArray(4.84,1)

We then define an instance of the SourceType class

In [3]:
pointSource4=SourceType(aLValues)

We now wish to define our configuration. There are several ways to proceed; as an example, we will use 6 sources.

First, we may work with SingleSource objects.
We define the single sources by their polar coordinates and relative strength (theta, phi, strength).

In [4]:
numSources=6

In [5]:
s1=SingleSource(0,0,1)
s2=SingleSource(0.1,0,1)
s3=SingleSource(0.2,0,1)
s4=SingleSource(0.3,0,1)
s5=SingleSource(0.4,0,1)
s6=SingleSource(0.5,0,1)

Next we define our sourceArray, and then define the configuration object from the number of sources, SourceType, and array.

In [6]:
sourceArray=np.array([s1,s2,s3,s4,s5,s6])
config1=Configuration(numSources,pointSource4,sourceArray=sourceArray)

Alternatively, we may already have the information in the form of a configuration vector, which has all of the thetas, then phis, then strengths.
A further option is sourceTuples, in the form of a tuple (or anything list-like) of ((theta,phi,strength),...)

In [7]:
configVectorExample=np.array([0,0.1,0.2,0.3,0.4,0.5,0,0,0,0,0,0,1,1,1,1,1,1])
config2=Configuration(numSources,pointSource4,configVector=configVectorExample)

sourceTuplesExample=((0,0,1),(0.1,0,1),(0.2,0,1),(0.3,0,1),(0.4,0,1),(0.5,0,1))
config3=Configuration(numSources,pointSource4,sourceTuples=sourceTuplesExample)

In [8]:
print(config1.configVector,config2.configVector,config3.configVector )

[0.  0.1 0.2 0.3 0.4 0.5 0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1. ] [0.  0.1 0.2 0.3 0.4 0.5 0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1. ] [0.  0.1 0.2 0.3 0.4 0.5 0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  1.  1. ]


Note that, to print with commas, you simple need to add repr()

In [9]:
print(repr(config1.configVector))

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0. , 0. , 0. , 0. , 0. , 0. , 1. ,
       1. , 1. , 1. , 1. , 1. ])


Lastly, we can generate a random starting configuration by supplying no initial information.

In [10]:
config4=Configuration(numSources,pointSource4)
print(repr(config4.configVector))

array([0.49251656, 3.016404  , 2.47929993, 2.56432034, 2.04632809,
       2.11818626, 3.77410122, 3.17671032, 5.29376344, 4.16524292,
       4.21222107, 2.74253207, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        ])


In [11]:
numLTerms=40
config1.sigmaRMSSqu(numLTerms)

2.6291118199684114

In [12]:
config1.sigmaRMSPercent(numLTerms)

162.1453613264472

## Optimizing the configuration

Now that we have our configuration, we define an instance of the Optimization class.
All settings are dealt with automatically - however, you will likely need to change the temp for good convergence. Aim to set the temp such that about 50% of basin hopping 'steps' are accepted.

In [13]:
optimizer=Optimization(config1,temp=0.0001)

To run numIterations steps of basin hopping:

In [14]:
numIterations=5
optimizer.optimize(numIterations)

basinhopping step 0: f 0.222397
basinhopping step 1: f 0.000241926 trial_f 0.000241926 accepted 1  lowest_f 0.000241926
found new global minimum on step 1 with function value 0.000241926
basinhopping step 2: f 0.000241924 trial_f 0.000241924 accepted 1  lowest_f 0.000241924
found new global minimum on step 2 with function value 0.000241924
basinhopping step 3: f 0.000241924 trial_f 0.000241924 accepted 1  lowest_f 0.000241924
basinhopping step 4: f 0.000241925 trial_f 0.000241925 accepted 1  lowest_f 0.000241924
basinhopping step 5: f 0.000241925 trial_f 0.000241925 accepted 1  lowest_f 0.000241924


array([-3.72063045, -1.48947076, -0.57907376,  0.99895715,  1.65211056,
        4.14057623,  0.67358504, -1.02227649,  0.67346443,  0.49606697,
       -1.02222192,  0.49607773,  1.7063689 ,  1.70624916,  1.70638724,
        1.70630758,  1.70634833,  1.70632365])

As it stands, this will update the initial configuration.

In [15]:
config1.configVector

array([-3.72063045, -1.48947076, -0.57907376,  0.99895715,  1.65211056,
        4.14057623,  0.67358504, -1.02227649,  0.67346443,  0.49606697,
       -1.02222192,  0.49607773,  1.7063689 ,  1.70624916,  1.70638724,
        1.70630758,  1.70634833,  1.70632365])

In [16]:
config1.sigmaRMSPercent(numLTerms)

1.5625771917917166

Note that the first run will typically take longer, whilst numba compiles the functions.  

## Reduced Degrees of Freedom

For larger numbers of sources, we can speed up convergence by only dealing with half the sources - for reasons why see the paper.
In this case, we define our configuration using the ConfigurationRDOF class.

In [17]:
configVectorRDOF=np.array([0,0.1,0.2,0,0,0,1,1,1])
configRDOF=ConfigurationRDOF(numSources,pointSource4,configVector=configVectorRDOF)

To recover full configuration vector/source array/source tuples:

In [18]:
configRDOF.fullConfigVector()
configRDOF.fullSourceArray()
configRDOF.fullSourceTuples()

[(0.0, 0.0, 1.0),
 (0.1, 0.0, 1.0),
 (0.2, 0.0, 1.0),
 (3.141592653589793, 3.141592653589793, 1.0),
 (3.041592653589793, 3.141592653589793, 1.0),
 (2.941592653589793, 3.141592653589793, 1.0)]

Can be optimized exactly as before.

In [19]:
optimizerRDOF=Optimization(configRDOF,temp=0.0001)
numIterations=5
optimizerRDOF.optimize(numIterations)

basinhopping step 0: f 0.222398
basinhopping step 1: f 0.000241923 trial_f 0.000241923 accepted 1  lowest_f 0.000241923
found new global minimum on step 1 with function value 0.000241923
basinhopping step 2: f 0.000241923 trial_f 0.000241923 accepted 1  lowest_f 0.000241923
found new global minimum on step 2 with function value 0.000241923
basinhopping step 3: f 0.000241923 trial_f 0.000241923 accepted 1  lowest_f 0.000241923
basinhopping step 4: f 0.000241923 trial_f 0.000241923 accepted 1  lowest_f 0.000241923
basinhopping step 5: f 0.000241923 trial_f 0.000241923 accepted 1  lowest_f 0.000241923


array([0.        , 1.57079631, 4.71238967, 0.        , 0.        ,
       1.57079694, 1.        , 0.99999912, 1.00000034])

In [20]:
configRDOF.sigmaRMSPercent(numLTerms)

1.5625755087710673

## Lasers

For lasers instead of point sources, all is identical, apart from the SourceType.
Laser type is defined by a super-gaussian (see paper).
Need to give etaPerp, beta, and alpha.

In [21]:
etaPerp=0.9
beta=5
alpha=0.95

aLValuesLaser=aLValuesLaserArray(etaPerp,beta,alpha)
laser=SourceType(aLValuesLaser)

From this point, all is equivalent to the pointSources.